### ISSUE TITLE
Add enemy projectiles

### ISSUE THREAD

**Issue by parasyte** [melonjs/tutorial-space-invaders#2]
As noted on [the forum](http://www.html5gamedevs.com/topic/32006-space-invaders-tutorial-adding-enemy-lasers-initial-position/), we're lacking enemy projectiles in the tutorial. It's not a complicated add, but creating a projectile outside of the enemy container can be tricky due to position inheritance.

**Comment by obiot** [comment]
leaving this for outside of the tutorial scope, based on how this is implemented for the player, it is reasonably easy to implement the same for enemies and definitely a good exercise/challenge
